name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GITHUB_TOKEN.USERNAME_DOCKER }}
          password: ${{ secrets.GITHUB_TOKEN.PASSWORD_DOCKER }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.GITHUB_TOKEN.USERNAME_DOCKER }}/my-app:latest

      - name: Deploy Container
        run: |
          docker run -d --name my-app -p 80:80 ${{ secrets.GITHUB_TOKEN.USERNAME_DOCKER }}/my-app:latest
